title: Space Rocks
description: The website for the ftc team 15303, Space Rocks
show_downloads: true
google_analytics:
theme: minima
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
